/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package one.dedic.jmri.roster.detail;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.function.Function;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import jmri.jmrit.roster.Roster;
import jmri.jmrit.roster.RosterEntry;

/**
 *
 * @author sdedic
 */
public class RosterDetailX extends javax.swing.JPanel {
    private final EntryModel model;
    private final RosterEntry entry;
    private Roster roster;
    
    private ComboBoxCompleter roadNameCompleter;
    private ComboBoxCompleter roadNumberCompleter;
    private ComboBoxCompleter mfgCompleter;
    private ComboBoxCompleter modelTypeCompleter;
    private ComboBoxCompleter ownerCompleter;
    
    
    /**
     * Creates new form RosterDetail
     */
    public RosterDetailX(EntryModel model) {
        this.model = model;
        this.entry = model.getEntry();
        initComponents();
        
        roadNameCompleter = new ComboBoxCompleter(roadName);
        roadNumberCompleter = new ComboBoxCompleter(roadNumber);
        mfgCompleter = new ComboBoxCompleter(manufacturer);
        modelTypeCompleter = new ComboBoxCompleter(type);
        ownerCompleter = new ComboBoxCompleter(owner);
    }
    
    public void setRoster(Roster roster) {
        this.roster = roster;
    }
    
    public void load() throws IOException {
        id.setText(entry.getId());
        description.setText(entry.getComment());
        decoderFamily.setText(entry.getDecoderFamily());
        decoderModel.setText(entry.getDecoderModel());
        notes.setText(entry.getDecoderComment());

        initUsedValues(roadName, RosterEntry::getRoadName);
        initUsedValues(roadNumber, RosterEntry::getRoadNumber);
        initUsedValues(manufacturer, RosterEntry::getMfg);
        initUsedValues(type, RosterEntry::getModel);
        initUsedValues(owner, RosterEntry::getOwner);
    }
    
    private void initUsedValues(JComboBox box, Function<RosterEntry,String> itemFactory) {
        box.setModel(createModel(itemFactory));
        box.getEditor().setItem(itemFactory.apply(entry));
    }
    
    private ComboBoxModel<String> createModel(Function<RosterEntry,String> itemFactory) {
        DefaultComboBoxModel<String> m = new DefaultComboBoxModel<>();
        Set<String> unique = new HashSet<>();
        for (RosterEntry e : roster.getAllEntries()) {
            String item = itemFactory.apply(e);
            if (item != null && !item.isEmpty()) {
                unique.add(item);
            }
        }
        List<String> sorted = new ArrayList<>(unique);
        Collections.sort(sorted);
        for (String s : sorted) {
            m.addElement(s);
        }
        return m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        id = new javax.swing.JTextField();
        roadName = new javax.swing.JComboBox<>();
        lRoadName = new javax.swing.JLabel();
        lID = new javax.swing.JLabel();
        roadNumber = new javax.swing.JComboBox<>();
        lRoadNumber = new javax.swing.JLabel();
        lManufacturer = new javax.swing.JLabel();
        lType = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lFamily = new javax.swing.JLabel();
        decoderFamily = new javax.swing.JTextField();
        stRoadNumber = new javax.swing.JLabel();
        stID = new javax.swing.JLabel();
        lModel = new javax.swing.JLabel();
        lDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        notes = new javax.swing.JTextArea();
        lNotes = new javax.swing.JLabel();
        lOwner = new javax.swing.JLabel();
        manufacturer = new javax.swing.JComboBox<>();
        type = new javax.swing.JComboBox<>();
        owner = new javax.swing.JComboBox<>();
        decoderModel = new javax.swing.JTextField();
        stOwner = new javax.swing.JLabel();

        id.setText(org.openide.util.NbBundle.getMessage(RosterDetailX.class, "RosterDetailX.id.text_3")); // NOI18N
        id.setNextFocusableComponent(roadName);

        roadName.setEditable(true);
        roadName.setNextFocusableComponent(roadNumber);

        org.openide.awt.Mnemonics.setLocalizedText(lRoadName, org.openide.util.NbBundle.getMessage(RosterDetailX.class, "RosterDetailX.lRoadName.text_3")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lID, org.openide.util.NbBundle.getMessage(RosterDetailX.class, "RosterDetailX.lID.text_3")); // NOI18N

        roadNumber.setEditable(true);
        roadNumber.setNextFocusableComponent(manufacturer);

        org.openide.awt.Mnemonics.setLocalizedText(lRoadNumber, org.openide.util.NbBundle.getMessage(RosterDetailX.class, "RosterDetailX.lRoadNumber.text_3")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lManufacturer, org.openide.util.NbBundle.getMessage(RosterDetailX.class, "RosterDetailX.lManufacturer.text_3")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lType, org.openide.util.NbBundle.getMessage(RosterDetailX.class, "RosterDetailX.lType.text_3")); // NOI18N

        jLabel6.setFont(jLabel6.getFont().deriveFont((jLabel6.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(RosterDetailX.class, "RosterDetailX.jLabel6.text_3")); // NOI18N

        jLabel7.setFont(jLabel7.getFont().deriveFont((jLabel7.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(RosterDetailX.class, "RosterDetailX.jLabel7.text_3")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lFamily, org.openide.util.NbBundle.getMessage(RosterDetailX.class, "RosterDetailX.lFamily.text_3")); // NOI18N

        decoderFamily.setEditable(false);
        decoderFamily.setBackground(getBackground());
        decoderFamily.setText(org.openide.util.NbBundle.getMessage(RosterDetailX.class, "RosterDetailX.decoderFamily.text_3")); // NOI18N

        stRoadNumber.setLabelFor(roadNumber);
        org.openide.awt.Mnemonics.setLocalizedText(stRoadNumber, org.openide.util.NbBundle.getMessage(RosterDetailX.class, "RosterDetailX.stRoadNumber.text_3")); // NOI18N

        stID.setLabelFor(id);
        org.openide.awt.Mnemonics.setLocalizedText(stID, org.openide.util.NbBundle.getMessage(RosterDetailX.class, "RosterDetailX.stID.text_3")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lModel, org.openide.util.NbBundle.getMessage(RosterDetailX.class, "RosterDetailX.lModel.text_3")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lDescription, org.openide.util.NbBundle.getMessage(RosterDetailX.class, "RosterDetailX.lDescription.text_3")); // NOI18N

        description.setColumns(20);
        description.setLineWrap(true);
        description.setRows(4);
        jScrollPane1.setViewportView(description);

        notes.setColumns(20);
        notes.setRows(4);
        jScrollPane2.setViewportView(notes);

        org.openide.awt.Mnemonics.setLocalizedText(lNotes, org.openide.util.NbBundle.getMessage(RosterDetailX.class, "RosterDetailX.lNotes.text_3")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lOwner, org.openide.util.NbBundle.getMessage(RosterDetailX.class, "RosterDetailX.lOwner.text_3")); // NOI18N

        manufacturer.setEditable(true);
        manufacturer.setNextFocusableComponent(type);

        type.setEditable(true);
        type.setNextFocusableComponent(description);

        owner.setEditable(true);

        decoderModel.setEditable(false);
        decoderModel.setBackground(getBackground());
        decoderModel.setText(org.openide.util.NbBundle.getMessage(RosterDetailX.class, "RosterDetailX.decoderModel.text_3")); // NOI18N

        stOwner.setLabelFor(owner);
        org.openide.awt.Mnemonics.setLocalizedText(stOwner, org.openide.util.NbBundle.getMessage(RosterDetailX.class, "RosterDetailX.stOwner.text_2")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(432, 432, 432)
                .addComponent(lModel, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addGap(306, 306, 306))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lRoadName, javax.swing.GroupLayout.PREFERRED_SIZE, 87, Short.MAX_VALUE))
                                    .addComponent(lRoadNumber))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roadName, 0, 207, Short.MAX_VALUE)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(roadNumber, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stID)
                                    .addComponent(stRoadNumber)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lFamily)
                                    .addComponent(lNotes))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(decoderFamily, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lManufacturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(type, 0, 264, Short.MAX_VALUE)
                                .addComponent(decoderModel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lDescription)
                                    .addComponent(lOwner))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(owner, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(stOwner))
                                    .addComponent(jScrollPane1))))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {decoderFamily, id, owner, roadName, roadNumber});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lID)
                    .addComponent(stID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roadName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lRoadName)
                    .addComponent(lManufacturer)
                    .addComponent(manufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lRoadNumber)
                            .addComponent(stRoadNumber)
                            .addComponent(lType)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(owner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lOwner)
                    .addComponent(stOwner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decoderFamily, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lModel)
                    .addComponent(lFamily)
                    .addComponent(decoderModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNotes))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField decoderFamily;
    private javax.swing.JTextField decoderModel;
    private javax.swing.JTextArea description;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lDescription;
    private javax.swing.JLabel lFamily;
    private javax.swing.JLabel lID;
    private javax.swing.JLabel lManufacturer;
    private javax.swing.JLabel lModel;
    private javax.swing.JLabel lNotes;
    private javax.swing.JLabel lOwner;
    private javax.swing.JLabel lRoadName;
    private javax.swing.JLabel lRoadNumber;
    private javax.swing.JLabel lType;
    private javax.swing.JComboBox<String> manufacturer;
    private javax.swing.JTextArea notes;
    private javax.swing.JComboBox<String> owner;
    private javax.swing.JComboBox<String> roadName;
    private javax.swing.JComboBox<String> roadNumber;
    private javax.swing.JLabel stID;
    private javax.swing.JLabel stOwner;
    private javax.swing.JLabel stRoadNumber;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
