/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package one.dedic.jmri.decodernext.ui;

/**
 *
 * @author sdedic
 */
public class FeedbackPanel extends javax.swing.JPanel {

    /**
     * Creates new form FeedbackPanel
     */
    public FeedbackPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contentArea = new javax.swing.JPanel();
        problemView = new javax.swing.JPanel();
        singleMessage = new javax.swing.JPanel();
        lOverview = new javax.swing.JLabel();
        btnMore = new javax.swing.JButton();
        acknowledged = new javax.swing.JCheckBox();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(contentArea, gridBagConstraints);

        problemView.setLayout(new java.awt.CardLayout());

        lOverview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/one/dedic/jmri/decodernext/resources/error.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lOverview, org.openide.util.NbBundle.getMessage(FeedbackPanel.class, "FeedbackPanel.lOverview.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnMore, org.openide.util.NbBundle.getMessage(FeedbackPanel.class, "FeedbackPanel.btnMore.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(acknowledged, org.openide.util.NbBundle.getMessage(FeedbackPanel.class, "FeedbackPanel.acknowledged.text")); // NOI18N

        javax.swing.GroupLayout singleMessageLayout = new javax.swing.GroupLayout(singleMessage);
        singleMessage.setLayout(singleMessageLayout);
        singleMessageLayout.setHorizontalGroup(
            singleMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleMessageLayout.createSequentialGroup()
                .addGroup(singleMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(singleMessageLayout.createSequentialGroup()
                        .addComponent(lOverview)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(singleMessageLayout.createSequentialGroup()
                        .addComponent(btnMore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addComponent(acknowledged)))
                .addContainerGap())
        );
        singleMessageLayout.setVerticalGroup(
            singleMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleMessageLayout.createSequentialGroup()
                .addComponent(lOverview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(singleMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMore)
                    .addComponent(acknowledged))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        problemView.add(singleMessage, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(problemView, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox acknowledged;
    private javax.swing.JButton btnMore;
    private javax.swing.JPanel contentArea;
    private javax.swing.JLabel lOverview;
    private javax.swing.JPanel problemView;
    private javax.swing.JPanel singleMessage;
    // End of variables declaration//GEN-END:variables
}
