/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package one.dedic.jmri.roster.impl;

import java.awt.Dimension;
import java.io.IOException;
import javax.swing.JPanel;
import javax.swing.event.ChangeListener;
import jmri.jmrit.roster.RosterEntry;
import one.dedic.jmri.decodernext.ui.ComposedPane;
import one.dedic.jmri.decodernext.ui.Section;
import one.dedic.jmri.decodernext.ui.ValidatingUI;
import one.dedic.jmri.roster.detail.EntryModel;
import one.dedic.jmri.roster.detail.RosterDetail;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.nodes.Node;
import org.openide.util.Exceptions;
import org.openide.util.ImageUtilities;

/**
 *
 * @author sdedic
 */
public class DecoderTopLayout extends javax.swing.JPanel {
    private final RosterEntry entry;
    private final EntryModel  entryModel;
    
    /**
     * Creates new form DecoderTopLayout
     */
    public DecoderTopLayout(EntryModel model) {
        this.entryModel = model;
        this.entry = model.getEntry();
        
        initComponents();
        
        ComposedPane cp = new ComposedPane();
        sectionGroups.addTab("General", ImageUtilities.loadImageIcon("one/dedic/jmri/decodernext/resources/general32.png", false), 
                cp);
        
        AbstractNode n = new AbstractNode(Children.LEAF);
        n.setName("Model Information");
        
        cp.addSection(new Section() {
            @Override
            public Object getKey() {
                return "Model Information";
            }

            @Override
            public Node getNode() {
                return n;
            }

            @Override
            public Dimension getSize() {
                return new Dimension(2, 1);
            }

            @Override
            public JPanel createComponent() {
                RosterDetail d = new RosterDetail(entryModel);
                d.setRoster(model.getRoster());
                try {
                    d.load();
                } catch (IOException ex) {
                    Exceptions.printStackTrace(ex);
                }
                return d;
            }

            @Override
            public ValidatingUI getValidation() {
                return null;
            }

            @Override
            public void addChangeListener(ChangeListener l) {
            }

            @Override
            public void removeChangeListener(ChangeListener l) {
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionToolbar = new javax.swing.JToolBar();
        sectionGroups = new javax.swing.JTabbedPane();

        actionToolbar.setRollover(true);

        sectionGroups.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        sectionGroups.setInheritsPopupMenu(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(actionToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sectionGroups, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(actionToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sectionGroups, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar actionToolbar;
    private javax.swing.JTabbedPane sectionGroups;
    // End of variables declaration//GEN-END:variables
}
